import i18n from "@/plugins/i18n";
import { state } from "@/store/state";

export const globals = {
  $filter_fields: (sets = {}) => {
    return [
      {
        name: "fk_governorate",
        company_level: 20,
        depend: false,
        type: "ForeignKey",
        null: sets?.null || false,
        label_ar: "المحافظة",
        label_en: "Governorate",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "OrgGovernorate",
        width: sets?.width || 12,
        model: "Governorate",
      },
      {
        name: "fk_directorate",
        company_level: 30,
        depend: false,
        type: "ForeignKey",
        null: sets?.null || false,
        label_ar: "المديرية",
        label_en: "المديرية",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "OrgDirectorate",
        width: sets?.width || 12,
        model: "Directorate",
      },
      // {
      //   name: "fk_region",
      //   company_level: 4,
      //   depend: false,
      //   type: "ForeignKey",
      //   null: sets?.null || false,
      //   label_ar: "المنطقة",
      //   label_en: "المديرية",
      //   max_length: null,
      //   default: null,
      //   icon: null,
      //   group: sets?.group || null,
      //   depend: false,
      //   name_list: "OrgRegion",
      //   width: sets?.width || 12,
      // },
      {
        name: "fk_school",
        company_level: 40,
        depend: false,
        type: "ForeignKey",
        null: sets?.null || false,
        label_ar: "المدرسة",
        label_en: "المدرسة",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "OrgSchoolByDirectorate",
        width: sets?.width || 4,
      },
      {
        name: "fk_branch",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: sets?.null || false,
        label_ar: "الفرع",
        label_en: "الفرع",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "OrgBranch",
        width: sets?.width || 3,
      },
      {
        name: "fk_year_of_study",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: sets?.null || false,
        label_ar: "السنة الدارسية",
        label_en: "Year Of Study",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "YearOfStudy",
        width: sets?.width || 6,
      },
      {
        name: "fk_section",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "القسم",
        label_en: "Section",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "Sections",
        width: sets?.width || "3",

      },
      {
        name: "fk_section_school",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "القسم",
        label_en: "Section",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "SectionsSchool",
        width: sets?.width || "3",

      },
      {
        name: "fk_branch_class",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصف",
        label_en: "Class",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "BranchClassByBranch",
        width: sets?.width || "3",
        model: "ClassDivisionHall",
      },
      {
        name: "fk_branch_class_ministerial",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصف",
        label_en: "Class",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "BranchClassMinisterial",
        width: sets?.width || "3",
        model: "ClassDivisionHall",
      },
      // {
      //   name: "fk_branch_class_promotion",
      //   company_level: 5,
      //   depend: false,
      //   type: "ForeignKey",
      //   null: false,
      //   label_ar: "الصف",
      //   label_en: "Class",
      //   max_length: null,
      //   default: null,
      //   icon: "",
      //   group: "filter",
      //   name_list: "BranchClassByBranchPromotion",
      //   width: sets?.width || "3",
      //   model: "ClassDivisionHall",
      // },
      {
        name: "fk_semester",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الترم",
        label_en: "Semester",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Semester",
        width: sets?.width || "3",
        model: "",
      },

      {
        name: "fk_branch_class_report",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصف",
        label_en: "Class",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "ClassReport",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_school_by_class",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصف",
        label_en: "Class",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "ClassBySchool",
        width: sets?.width || "3",
        model: "ClassDivisionHall",
      },
      {
        name: "fk_branch_by_class",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصفوف حسب الفرع",
        label_en: "Class",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "ClassByBranch",
        width: sets?.width || "3",
        model: "ClassDivisionHall",
      },

      {
        name: "fk_class",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصف",
        label_en: "Class",
        max_length: null,
        default: null,
        icon: "",
        group: "filter",
        name_list: "Class",
        width: "3",
        model: "Class",
      },
      {
        name: "fk_class_division_hall",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الشعبة",
        label_en: "Division",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "ClassDivisionHallByBranchClass",
        width: sets?.width || "3",
        model: "ClassDivisionHall",
      },
      {
        name: "fk_branch_class_subject",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "المادة",
        label_en: "Subject",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "BranchClassSubjectByBranchClass",
        width: sets?.width || "3",
        model: "BranchClassSubject",
      },
      {
        name: "fk_class_subject",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "المادة",
        label_en: "Subject",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "ClassSubjectByClass",
        width: sets?.width || "3",
        model: "ClassSubject",
      },
      {
        name: "fk_address",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "العنوان",
        label_en: "Address",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "AddressByRegion",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_address_by_class",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "العنوان",
        label_en: "Address",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "AddressByClass",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "month_semester",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الاشهر",
        label_en: "month",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "SemesterPlanMonth",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_homework",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الواجبات",
        label_en: "Homework",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Homework",
        width: sets?.width || "3",
        model: "Homework",
      },
      {
        name: "subject_by_class_division",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "المواد",
        label_en: "Subject",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "SubjectByClassDivision",
        width: sets?.width || "3",
        model: "Homework",
      },
      {
        name: "fk_document",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الوثيقة",
        label_en: "Document",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Archive",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_committee",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اللجنة",
        label_en: "Committee",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "CommitteesByBranchClass",
        width: sets?.width || "3",
        model: "",
      },
      //الطلاب حسب الصف
      {
        name: "fk_student_by_class",
        company_level: 50,
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الطالب",
        label_en: "Student",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "StudentByClass",
        width: sets?.width || "3",
        model: "StudentClass",
      },
      //الطلاب حسب الشعبة
      {
        name: "fk_student_by_division",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الطالب",
        label_en: "Student",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "StudentByClassDivisionHall",
        width: sets?.width || "3",
        model: "StudentClass",
      },
      // الطلاب حسب الشعبة او الصف
      {
        name: "fk_student_by_division_or_class",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الطالب",
        label_en: "Student",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "StudentByClassDivisionHallAndClass",
        width: sets?.width || "3",
        model: "StudentClass",
      },
      {
        name: "fk_month",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الشهر",
        label_en: "Month",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Months",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_month_h",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الشهر",
        label_en: "Month",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "MonthsHijri",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_bus",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الباص",
        label_en: "Bus",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Buses",
        width: sets?.width || "3",
        model: "bus",
      },

      {
        name: "estimation",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "التقدير",
        label_en: "Estimate",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Estimate",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_fees_type",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "انواع الرسوم",
        label_en: "Fee Type",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "FeeType",
        width: sets?.width || "3",
        model: "",
      },

      {
        name: "fk_activity",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الأنشطة",
        label_en: "Activity",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Activity",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_activity_branch",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الأنشطة",
        label_en: "Activity",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "ActivityByBranch",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "committee",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اللجنة",
        label_en: "Committee",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Committees",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_exam_periods",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الفترة",
        label_en: "ExamPeriods",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "ExamPeriods",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "get_dates",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "التاريخ",
        label_en: "GetDates",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "GetDates",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "get_committee",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اللجنة",
        label_en: "committee",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "CommitteeByExam",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "setting_committees",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اللجنة",
        label_en: "committee",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "SettingCommittees",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_guardian",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اولياء الامور",
        label_en: "Guardians",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "Guardians",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_guardian_school",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اولياء الامور",
        label_en: "Guardians",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "GuardiansBySchool",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_guardian_branch",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اولياء الامور",
        label_en: "Guardians",
        max_length: null,
        default: null,
        icon: null,
        group: "filter",
        name_list: "GuardiansBybranch",
        width: sets?.width || "3",
        model: "",
      },
      {
        name: "fk_year_of_study_hijri",
        depend: false,
        type: "ForeignKey",
        null: true,
        label_ar: "السنة الدارسية",
        label_en: "Year Of Study",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "YearOfStudyHijri",
        width: sets?.width || 6,
      },
      {
        name: "fk_class_ministerial",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الصف",
        label_en: "Class Ministerial",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "ClassMinisterial",
        width: sets?.width || 6,
      },
      {
        name: "fk_exam_center",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "المركز الاختباري",
        label_en: "Exam Center",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "ExamCenter",
        width: sets?.width || 6,
      },
      {
        name: "fk_exam_schedule",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "جدول الاختبارات ",
        label_en: "Exam Schedule",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "ExamSchedule",
        width: sets?.width || 6,
      },
      {
        name: "fk_exams_committee",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "اللجان ",
        label_en: "Exams Committee",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "ExamsCommittee",
        width: sets?.width || 6,
      },
      {
        name: "fk_exams_period",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الفتره ",
        label_en: "Exams Period ",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "ExamsPeriod",
        width: sets?.width || 6,
      },
      {
        name: "date_period",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "التاريخ ",
        label_en: "Date Period ",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "DatePeriod",
        width: sets?.width || 6,
      },
      {
        name: "role",
        depend: false,
        type: "ForeignKey",
        null: false,
        label_ar: "الدور ",
        label_en: "role ",
        max_length: null,
        default: null,
        icon: null,
        group: sets?.group || null,
        name_list: "RoleEmployee",
        width: sets?.width || 6,
      },
    ].filter(
      (field) =>
        field?.company_level >= state?.profile?.zi || !field?.company_level
    );
  },
  $start_date_before_end: (start, end) => {
    if (!start || !end) return true;

    const [s_day, s_month, s_year] = start.split("-").map(Number);
    const [e_day, e_month, e_year] = end.split("-").map(Number);

    const startDate = new Date(s_year, s_month - 1, s_day);
    const endDate = new Date(e_year, e_month - 1, e_day);

    return (
      startDate < endDate || i18n.global.t("start_date_must_be_before_end")
    );
  },
  $duplicateView: (items) => (value) => {
    if (!value) return true;
    if (items) {
      const data = items.some(
        (e) => e == value && e !== "" && e !== null && e !== undefined
      );
      if (data.length > 0) {
        return "البيانات مكررة";
      }
    }
    return true;
  },

  $validate: async (ref) => {
    if (typeof ref == "object") {
      const { valid } = await ref?.validate();
      return valid;
    }
    return false;
  },

  $duplicateAdd: (items) => (value) => {
    if (!value) return true;
    if (items) {
      const data = items.filter(
        (e) => e == value && e !== "" && e !== null && e !== undefined
      );
      if (data.length > 1) {
        return "البيانات مكررة";
      }
    }
    return true;
  },
  // dublicate items
  $checkDuplicate: (value, items, key, currentId = null) => {
    if (!value) return true;
    const list = Array.isArray(items)
      ? items
      : Array.isArray(items.results)
      ? items.results
      : [];
    const exists = list.some(
      (item) => item[key] === value && item.id !== currentId
    );
    return exists ? "القيمة موجودة مسبقاً" : true;
  },
  //ex getData
  //async getData(params = this.$params) {
  //return await this.$axios(this.url, params).then((response) => {
  //this.items = response.data;
  //this.allItems = Array.isArray(this.items)
  //? this.items
  //: Array.isArray(this.items.results)
  //? this.items.results
  //  : [];
  //});
  //},

  $date_format: (value) => {
    if (!value) return i18n.global.t("required_field");

    let cleaned = String(value).replace(/\D/g, "");

    const day = cleaned.substring(0, 2);
    const month = cleaned.substring(2, 4);
    const year = cleaned.substring(4, 8);

    let formatted = day;
    if (month) formatted += "-" + month;
    if (year) formatted += "-" + year;

    if (formatted.length > 10) return i18n.global.t("date_too_long");
    if (cleaned.length < 8) return formatted;

    if (!/^\d{2}-\d{2}-\d{4}$/.test(formatted))
      return i18n.global.t("invalid_date_format");

    const date = new Date(`${year}-${month}-${day}`);
    if (
      !(
        date &&
        date.getFullYear() === parseInt(year) &&
        date.getMonth() + 1 === parseInt(month) &&
        date.getDate() === parseInt(day)
      )
    ) {
      return i18n.global.t("invalid_date");
    }
    return formatted;
  },
};
